### ISSUE TITLE
Add ssh

### ISSUE THREAD

**Issue by skyscooby** [jumanjihouse/docker-rancid-git#11]
please apk add ssh so that rancid can reach out to devices as this seems very important

**Comment by jumanjiman** [comment]
@skyscooby 

Thanks for the request. Makes sense to me.

A new image tag is available at https://hub.docker.com/r/jumanjiman/rancid/tags/ with the ssh client:
* 3.7-r0_20180705T1141_git_f24c320

**Comment by jumanjiman** [comment]
Resolved via https://github.com/jumanjihouse/docker-rancid-git/pull/12
